Repository v-pos/vpos-woocommerce, pull requests merged in 2021-04, with the labels that each got.

#1 move conditional check before usage
  handle.php
Labels: enhancement

#2 Fix wordpress path issue
  vpos-checkout.php
Labels: bug

#4 POST URL
  .gitignore
  handle.php
  payment_gateway.php
  vpos-checkout.php
  vpos-payment-gateway.php
Labels: bug, enhancement
